services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
      - 80:3000
      - 443:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    environment:
      - NTFY_ENABLE_LOGIN=true
      - NTFY_AUTH_FILE=/var/lib/ntfy_auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
    command:
      - serve
    ports:
      - 6520:80
    restart: unless-stopped
    volumes:
      - ntfy_config:/etc/ntfy
      - ntfy_cache:/var/cache/ntfy
      - ntfy_auth:/var/lib/ntfy_auth.db
volumes:
  prom_data:
  grafana_data:
  ntfy_config:
  ntfy_cache:
  ntfy_auth: